### ISSUE TITLE
19 files import lume/core/utils.ts, which was removed

### ISSUE THREAD

**Issue by teleclimber** [lumeland/experimental-plugins#32]
My test build doesn't work with the simple blog theme because it depends on a plugin from here which requests `core/utils.ts`.

It appears this file was removed in November: https://github.com/lumeland/lume/commit/75af978913b31348d1950534fd7ecafda5b9dbe7

It appears multiple plugins try to import this module.

**Comment by oscarotero** [comment]
`core/utils.ts` was removed in Lume 2 and the experimental plugins in this repo are created for Lume 1.

If you update the `simple_blog` theme to the latest version (`0.14.0`) it should work fine.

**Comment by teleclimber** [comment]
Ah ok thank  you. I was confused because the github repo for simple blog shows the latest release as 0.10.2, and the Readme example uses that version too. It's only on deno.land/x/ that 0.14 shows up.
